# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
env:
  ALLURE_VERSION: "2.10.0"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

  build:
    needs: setup
    steps:
    - name: Build with Maven
      id: build
      run: mvn -B package --file pom.xml

    - name: Get Allure history
      id: allure-setup
      if: steps.build.outcome == 'success'
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

  test:
    needs: build
    if: steps.allure-setup.outcome == 'success'
    runs-on: ubuntu-latest
    steps:
    - name: Tests
      timeout-minutes: 20
      continue-on-error: true
      run: mvn clean install

  report:
    needs: test
    steps:
    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: target/allure-results
        allure_history: allure-history

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-results
        